language: r

sudo: false

cache: packages

r_packages:
  - covr

after_success:
  - Rscript covr.R

branches:
  only:
    - master
    - development
    - rc
    - issue50

matrix:
  include:
    - r: 3.2
      if: branch = rc
    - r: 3.3
      if: branch = rc
    - r: oldrel
      if: branch = rc
    - r: release
    - r: devel
