language: r
r:
  - oldrel
  - release
  - devel

sudo: false

cache: packages

r_packages:
  - covr

branches:
  only:
    - master
    - development
    - rc

after_success:
  - Rscript covr.R

after_failure:
  - find . -name run*.Rout* | xargs cat
